### PR TITLE
2 new notebooks + small changes to osiris.py

### PR DESCRIPTION
**Pull request by tsung1029**
cleaned up osiris.py a little, plus made 2 new notebooks for two-stream and Buneman instability using UPIC-ES.

### CODE REVIEW

**Comment by benjum** [comment]
These look like good contributions.  However, in keeping with the educational nature of these notebooks, I think it would be good to:
1) move general diagnostics (such as time vs k) from notebook cells into osiris.py
2) include more information about the simulation set-up, and specify more clearly what parameters are changing between cases
3) include comments and/or questions with the plots to stimulate interactivity

**Comment by benjum** [comment]
I manually merged in tsung1029/JupyterPIC to resolve conflicts.  However, there is a separate osiris.py analysis file in the two-stream folder which is different from the analysis/osiris.py file.  Please integrate those into one analysis/osiris.py file.

**Comment by tsung1029** [comment]
Thanks Ben: 

Actually it is not quite ready. I put mine up in the fork so Kyle can provide some comments. I think it will be done tonight and we will work on Buneman next. 

Frank 


----- Original Message -----

**Comment by tsung1029** [comment]
and I will need your help then for sure, my fork looks very different from the current version. -- Frank 


----- Original Message -----

**Comment by benjum** [comment]
You may want to get the latest update from your repo -- I pushed the merged version directly there.

**Comment by tsung1029** [comment]
Yeah, I have a little trouble with that, I cannot make a new fork. When you are here you can show me how to make another fork. Thanks. 

Frank 


----- Original Message -----

**Comment by benjum** [comment]
I reverted the commit to your repo so that you can continue working with it.  I'll stop by tomorrow and we can talk about it.
--Ben

**Comment by tsung1029** [comment]
I've made a more polished 2 stream notebook, and osiris.py has been modified to include the two-stream functionality.

**Comment by tsung1029** [comment]
the new material is in the 2 stream folder and osiris.py.

**Comment by benjum** [comment]
I have manually merged the pull request files.  Thanks Frank!

**Pull request closed without merging**
