### PR TITLE
Single particle

### PR DESCRIPTION
**Pull request by millerk123**
Adding fftw library, new osiris-2D.e executable for Single-Particle workbook, and more streamlined notebook.  Includes Warren's edits to text.

### CODE REVIEW

**Comment by benjum** [comment]
@millerk123 - Thanks for the changes.

With regard to the fftw files, currently none of the source code files for our codes are included in this repo, and the compilers and libraries are handled by installing them inside the docker image.  Is it possible to do this for the fftw files?  or do you think that they need to be included here among the notebooks and analysis files?

**Comment by millerk123** [comment]
They definitely don't need to be among the notebooks and analysis files.  I
just don't know how to commit the change to the docker image.  Or how to
install in the docker image, for that matter.  I only had permission to
create a folder under /home/jovyan, which is where I put it.

Kyle

**Comment by benjum** [comment]
Ok.  We can chat offline about how to do this.

**Comment by benjum** [comment]
Thanks for all the changes!  One very minor further request -- can you please also copy the changed material into the notebooks-USPAS folder?

**Comment by millerk123** [comment]
Okay, should be good to go now!

**Pull request merged**
